[world]
description = "jokers_of_neon_mods"
name = "jokers_of_neon_mods"
seed = "jokers_of_neon_mods"

[namespace]
default = "jokers_of_neon_mods"

[env]
rpc_url = "https://api.cartridge.gg/x/jokers-of-neon-mods/katana"
# Default account for katana with seed = 0
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"

[writers]
"jokers_of_neon_mods" = [
    "jokers_of_neon_mods-mod_manager",
    "jokers_of_neon_mods-rage_manager",
    "jokers_of_neon_mods-special_manager",
]
