[package]
cairo-version = "=2.8.4"
name = "jokers_of_neon_mods"
version = "0.0.1"

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }
jokers_of_neon_lib = { git = "https://github.com/caravana-studio/jokers-of-neon-lib", branch="tournament" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }

[profile.prod]

[lib]
