[world]
description = "jokers_of_neon_classic"
name = "jokers_of_neon_classic"
seed = "jokers_of_neon_classic"

[namespace]
default = "jokers_of_neon_classic"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"
